export let DUMMY_WAREHOUSES = [
  {
    city: "New York",
    stateCode: "NY",
    volumeCapacity: 1000000,
    volumeUnits: "cubic feet",
    manager: "Phillip Yager",
    phone: "8056543321",
    id: 1,
    inventory: [
      {
        city: "New York",
        name: "Monitor",
        sku: 123,
        volume: 5,
        volumeUnits: "cubic feet",
        price: 119.99,
        currency: "USD",
        imageUrl:
          "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
        quantity: 243,
      },
      {
        city: "New York",
        name: "Chair",
        sku: 124,
        volume: 10,
        volumeUnits: "cubic feet",
        price: 189.99,
        currency: "USD",
        imageUrl:
          "https://secure.img1-fg.wfcdn.com/im/96489692/resize-h600-w600%5Ecompr-r85/9470/94709448/Office+Chairs.jpg",
        quantity: 122,
      },
      {
        city: "New York",
        name: "Desk",
        sku: 125,
        volume: 20,
        volumeUnits: "cubic feet",
        price: 419.99,
        currency: "USD",
        imageUrl:
          "https://image-proxy.production.mor.merce.io/800,fit,q80,jpeg/https://images.morfurniture.com/media/catalog/product/canto/PUR_480-2.jpg",
        quantity: 88,
      },
    ],
  },

  {
    city: "Miami",
    stateCode: "FL",
    volumeCapacity: 2000000,
    volumeUnits: "cubic feet",
    manager: "Stanley Hubertson",
    phone: "2345577777",
    id: 2,
    inventory: [
      {
        city: "Miami",
        name: "Monitor",
        sku: 123,
        volume: 5,
        volumeUnits: "cubic feet",
        price: 119.99,
        currency: "USD",
        imageUrl:
          "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
        quantity: 243,
      },
      {
        city: "Miami",
        name: "Chair",
        sku: 124,
        volume: 10,
        volumeUnits: "cubic feet",
        price: 189.99,
        currency: "USD",
        imageUrl:
          "https://secure.img1-fg.wfcdn.com/im/96489692/resize-h600-w600%5Ecompr-r85/9470/94709448/Office+Chairs.jpg",
        quantity: 122,
      },
      {
        city: "Miami",
        name: "Desk",
        sku: 125,
        volume: 20,
        volumeUnits: "cubic feet",
        price: 419.99,
        currency: "USD",
        imageUrl:
          "https://image-proxy.production.mor.merce.io/800,fit,q80,jpeg/https://images.morfurniture.com/media/catalog/product/canto/PUR_480-2.jpg",
        quantity: 88,
      },
    ],
  },

  {
    city: "Los Angeles",
    stateCode: "CA",
    volumeCapacity: 3000000,
    volumeUnits: "cubic feet",
    manager: "Mikey Mike",
    phone: "9807113619",
    id: 3,
    inventory: [
      {
        city: "Los Angeles",
        name: "Monitor",
        sku: 123,
        volume: 5,
        volumeUnits: "cubic feet",
        price: 119.99,
        currency: "USD",
        imageUrl:
          "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
        quantity: 243,
      },
      {
        city: "Los Angeles",
        name: "Chair",
        sku: 124,
        volume: 10,
        volumeUnits: "cubic feet",
        price: 189.99,
        currency: "USD",
        imageUrl:
          "https://secure.img1-fg.wfcdn.com/im/96489692/resize-h600-w600%5Ecompr-r85/9470/94709448/Office+Chairs.jpg",
        quantity: 122,
      },
      {
        city: "Los Angeles",
        name: "Desk",
        sku: 125,
        volume: 20,
        volumeUnits: "cubic feet",
        price: 419.99,
        currency: "USD",
        imageUrl:
          "https://image-proxy.production.mor.merce.io/800,fit,q80,jpeg/https://images.morfurniture.com/media/catalog/product/canto/PUR_480-2.jpg",
        quantity: 88,
      },
    ],
  },

  {
    city: "Boise",
    stateCode: "ID",
    volumeCapacity: 2500000,
    volumeUnits: "cubic feet",
    manager: "Phillip Yager",
    phone: "8056543321",
    id: 4,
    inventory: [
      {
        city: "Boise",
        name: "Monitor",
        sku: 123,
        volume: 5,
        volumeUnits: "cubic feet",
        price: 119.99,
        currency: "USD",
        imageUrl:
          "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
        quantity: 243,
      },
      {
        city: "Boise",
        name: "Chair",
        sku: 124,
        volume: 10,
        volumeUnits: "cubic feet",
        price: 189.99,
        currency: "USD",
        imageUrl:
          "https://secure.img1-fg.wfcdn.com/im/96489692/resize-h600-w600%5Ecompr-r85/9470/94709448/Office+Chairs.jpg",
        quantity: 122,
      },
      {
        city: "Boise",
        name: "Desk",
        sku: 125,
        volume: 20,
        volumeUnits: "cubic feet",
        price: 419.99,
        currency: "USD",
        imageUrl:
          "https://image-proxy.production.mor.merce.io/800,fit,q80,jpeg/https://images.morfurniture.com/media/catalog/product/canto/PUR_480-2.jpg",
        quantity: 88,
      },
    ],
  },

  {
    city: "Richmond",
    stateCode: "VA",
    volumeCapacity: 3200000,
    volumeUnits: "cubic feet",
    manager: "Phillip Yager",
    phone: "8056543321",
    id: 5,
    inventory: [
      {
        city: "Richmond",
        name: "Monitor",
        sku: 123,
        volume: 5,
        volumeUnits: "cubic feet",
        price: 119.99,
        currency: "USD",
        imageUrl:
          "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
        quantity: 243,
      },
      {
        city: "Richmond",
        name: "Chair",
        sku: 124,
        volume: 10,
        volumeUnits: "cubic feet",
        price: 189.99,
        currency: "USD",
        imageUrl:
          "https://secure.img1-fg.wfcdn.com/im/96489692/resize-h600-w600%5Ecompr-r85/9470/94709448/Office+Chairs.jpg",
        quantity: 122,
      },
      {
        city: "Richmond",
        name: "Desk",
        sku: 125,
        volume: 20,
        volumeUnits: "cubic feet",
        price: 419.99,
        currency: "USD",
        imageUrl:
          "https://image-proxy.production.mor.merce.io/800,fit,q80,jpeg/https://images.morfurniture.com/media/catalog/product/canto/PUR_480-2.jpg",
        quantity: 88,
      },
    ],
  },
];
