let DUMMY_ITEMS = [
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "1",
  },
  {
    city: "New York",
    name: "Chair",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "In Transit",
    id: "2",
  },
  {
    city: "New York",
    name: "Desk",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Loading Bay",
    id: "3",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "4",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "5",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "6",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "7",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "8",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "9",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "10",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "11",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "12",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "13",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "14",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "15",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "16",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "17",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "18",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "19",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "20",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "21",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "22",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "23",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "24",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "25",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "26",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "27",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "28",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "29",
  },
  {
    city: "New York",
    name: "Monitor",
    sku: 123,
    volume: 5,
    volumeUnits: "cubic feet",
    price: 119.99,
    currency: "USD",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "Storage",
    id: "30",
  },
];

let DUMMY_WAREHOUSES = [
  {
    city: "New York",
    stateCode: "NY",
    volumeCapacity: 1000000,
    volumeUnits: "cubic feet",
    manager: "Phillip Yager",
    phone: "8056543321",
    id: 1,
    inventory: [
      {
        city: "New York",
        name: "Monitor",
        sku: 123,
        volume: 5,
        volumeUnits: "cubic feet",
        price: 119.99,
        currency: "USD",
        imageUrl:
          "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
        quantity: 243,
      },
      {
        city: "New York",
        name: "Chair",
        sku: 124,
        volume: 10,
        volumeUnits: "cubic feet",
        price: 189.99,
        currency: "USD",
        imageUrl:
          "https://secure.img1-fg.wfcdn.com/im/96489692/resize-h600-w600%5Ecompr-r85/9470/94709448/Office+Chairs.jpg",
        quantity: 122,
      },
      {
        city: "New York",
        name: "Desk",
        sku: 125,
        volume: 20,
        volumeUnits: "cubic feet",
        price: 419.99,
        currency: "USD",
        imageUrl:
          "https://image-proxy.production.mor.merce.io/800,fit,q80,jpeg/https://images.morfurniture.com/media/catalog/product/canto/PUR_480-2.jpg",
        quantity: 88,
      },
    ],
  },

  {
    city: "Miami",
    stateCode: "FL",
    volumeCapacity: 2000000,
    volumeUnits: "cubic feet",
    manager: "Stanley Hubertson",
    phone: "2345577777",
    id: 2,
    inventory: [
      {
        city: "Miami",
        name: "Monitor",
        sku: 123,
        volume: 5,
        volumeUnits: "cubic feet",
        price: 119.99,
        currency: "USD",
        imageUrl:
          "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
        quantity: 131,
      },
      {
        city: "Miami",
        name: "Chair",
        sku: 124,
        volume: 10,
        volumeUnits: "cubic feet",
        price: 189.99,
        currency: "USD",
        imageUrl:
          "https://secure.img1-fg.wfcdn.com/im/96489692/resize-h600-w600%5Ecompr-r85/9470/94709448/Office+Chairs.jpg",
        quantity: 12,
      },
      {
        city: "Miami",
        name: "Desk",
        sku: 125,
        volume: 20,
        volumeUnits: "cubic feet",
        price: 419.99,
        currency: "USD",
        imageUrl:
          "https://image-proxy.production.mor.merce.io/800,fit,q80,jpeg/https://images.morfurniture.com/media/catalog/product/canto/PUR_480-2.jpg",
        quantity: 440,
      },
    ],
  },

  {
    city: "Los Angeles",
    stateCode: "CA",
    volumeCapacity: 3000000,
    volumeUnits: "cubic feet",
    manager: "Mikey Mike",
    phone: "9807113619",
    id: 3,
    inventory: [
      {
        city: "Los Angeles",
        name: "Monitor",
        sku: 123,
        volume: 5,
        volumeUnits: "cubic feet",
        price: 119.99,
        currency: "USD",
        imageUrl:
          "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
        quantity: 22,
      },
      {
        city: "Los Angeles",
        name: "Chair",
        sku: 124,
        volume: 10,
        volumeUnits: "cubic feet",
        price: 189.99,
        currency: "USD",
        imageUrl:
          "https://secure.img1-fg.wfcdn.com/im/96489692/resize-h600-w600%5Ecompr-r85/9470/94709448/Office+Chairs.jpg",
        quantity: 12,
      },
      {
        city: "Los Angeles",
        name: "Desk",
        sku: 125,
        volume: 20,
        volumeUnits: "cubic feet",
        price: 419.99,
        currency: "USD",
        imageUrl:
          "https://image-proxy.production.mor.merce.io/800,fit,q80,jpeg/https://images.morfurniture.com/media/catalog/product/canto/PUR_480-2.jpg",
        quantity: 59,
      },
    ],
  },

  {
    city: "Boise",
    stateCode: "ID",
    volumeCapacity: 2500000,
    volumeUnits: "cubic feet",
    manager: "Phillip Yager",
    phone: "8056543321",
    id: 4,
    inventory: [
      {
        city: "Boise",
        name: "Monitor",
        sku: 123,
        volume: 5,
        volumeUnits: "cubic feet",
        price: 119.99,
        currency: "USD",
        imageUrl:
          "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
        quantity: 2,
      },
      {
        city: "Boise",
        name: "Chair",
        sku: 124,
        volume: 10,
        volumeUnits: "cubic feet",
        price: 189.99,
        currency: "USD",
        imageUrl:
          "https://secure.img1-fg.wfcdn.com/im/96489692/resize-h600-w600%5Ecompr-r85/9470/94709448/Office+Chairs.jpg",
        quantity: 36,
      },
      {
        city: "Boise",
        name: "Desk",
        sku: 125,
        volume: 20,
        volumeUnits: "cubic feet",
        price: 419.99,
        currency: "USD",
        imageUrl:
          "https://image-proxy.production.mor.merce.io/800,fit,q80,jpeg/https://images.morfurniture.com/media/catalog/product/canto/PUR_480-2.jpg",
        quantity: 81,
      },
    ],
  },

  {
    city: "Richmond",
    stateCode: "VA",
    volumeCapacity: 3200000,
    volumeUnits: "cubic feet",
    manager: "Phillip Yager",
    phone: "8056543321",
    id: 5,
    inventory: [
      {
        city: "Richmond",
        name: "Monitor",
        sku: 123,
        volume: 5,
        volumeUnits: "cubic feet",
        price: 119.99,
        currency: "USD",
        imageUrl:
          "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HMUA2_AV1?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1563859125527",
        quantity: 243,
      },
      {
        city: "Richmond",
        name: "Chair",
        sku: 124,
        volume: 10,
        volumeUnits: "cubic feet",
        price: 189.99,
        currency: "USD",
        imageUrl:
          "https://secure.img1-fg.wfcdn.com/im/96489692/resize-h600-w600%5Ecompr-r85/9470/94709448/Office+Chairs.jpg",
        quantity: 122,
      },
      {
        city: "Richmond",
        name: "Desk",
        sku: 125,
        volume: 20,
        volumeUnits: "cubic feet",
        price: 419.99,
        currency: "USD",
        imageUrl:
          "https://image-proxy.production.mor.merce.io/800,fit,q80,jpeg/https://images.morfurniture.com/media/catalog/product/canto/PUR_480-2.jpg",
        quantity: 88,
      },
    ],
  },
];

export { DUMMY_WAREHOUSES, DUMMY_ITEMS };
